_target_: solvers.openrouter_solver_reasoning.OpenrouterSolver
name: anthropic/claude-sonnet-4.5
model: anthropic/claude-sonnet-4.5
low_res_mode: False
api_key: openrouter
api_yaml: "${basic.api_yaml}"
image_root: "${basic.image_root}"
debug_mode: "${basic.debug_mode}"