_target_: solvers.gpt4o_solver.GPT4OSolver
name: gpt-4o-2024-05-13
low_res_mode: False
model: "gpt-4o-2024-05-13"
organization: "***"  # replace with a specific OpenAI organization ID if required
api_key: "***"                # replace with your OpenAI API key
image_root: "${basic.image_root}"
debug_mode: "${basic.debug_mode}"
