_target_: solvers.gpt5_solver.GPT5Solver
name: gpt-5-2025-08-07
low_res_mode: False
model: "gpt-5-2025-08-07"
organization: "***"  # replace with a specific OpenAI organization ID if required
api_key: "***"                # replace with your OpenAI API key
image_root: "${basic.image_root}"
debug_mode: "${basic.debug_mode}"