_target_: solvers.caption_aggregation_solver.CaptionAggregationSolver
name: language_only_baseline
huggingface_model_id: meta-llama/Meta-Llama-3.1-8B-Instruct # ensure you have LLama3's access
image_root: "${basic.image_root}"
debug_mode: "${basic.debug_mode}"
