# vLLM does not support this model
_target_: solvers.mplug_owl_solver.MPLUGSolver
name: mPLUG-Owl3-7B-240728
huggingface_model_id: mPLUG/mPLUG-Owl3-7B-240728
image_root: "${basic.image_root}"
debug_mode: "${basic.debug_mode}"
